# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keyactioneditwnd.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KeyActionEditDialog(object):
    def setupUi(self, KeyActionEditDialog):
        KeyActionEditDialog.setObjectName("KeyActionEditDialog")
        KeyActionEditDialog.resize(471, 164)
        self.gridLayout = QtWidgets.QGridLayout(KeyActionEditDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(KeyActionEditDialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.ok = QtWidgets.QPushButton(KeyActionEditDialog)
        self.ok.setAutoDefault(False)
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(KeyActionEditDialog)
        self.cancel.setAutoDefault(False)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_3.addWidget(self.cancel)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.keyEdit = QtWidgets.QLineEdit(KeyActionEditDialog)
        self.keyEdit.setObjectName("keyEdit")
        self.horizontalLayout.addWidget(self.keyEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(KeyActionEditDialog)
        QtCore.QMetaObject.connectSlotsByName(KeyActionEditDialog)

    def retranslateUi(self, KeyActionEditDialog):
        _translate = QtCore.QCoreApplication.translate
        KeyActionEditDialog.setWindowTitle(_translate("KeyActionEditDialog", "Key Action Dialog"))
        self.label.setText(_translate("KeyActionEditDialog", "Key (Combination):"))
        self.ok.setText(_translate("KeyActionEditDialog", "OK"))
        self.cancel.setText(_translate("KeyActionEditDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    KeyActionEditDialog = QtWidgets.QDialog()
    ui = Ui_KeyActionEditDialog()
    ui.setupUi(KeyActionEditDialog)
    KeyActionEditDialog.show()
    sys.exit(app.exec_())
