# Form implementation generated from reading ui file 'profileeditwnd.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ProfileEditDialog(object):
    def setupUi(self, ProfileEditDialog):
        ProfileEditDialog.setObjectName("ProfileEditDialog")
        ProfileEditDialog.resize(1191, 591)
        self.gridLayout_2 = QtWidgets.QGridLayout(ProfileEditDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=ProfileEditDialog)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.profileNameEdit = QtWidgets.QLineEdit(parent=ProfileEditDialog)
        self.profileNameEdit.setObjectName("profileNameEdit")
        self.horizontalLayout.addWidget(self.profileNameEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=ProfileEditDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.cmdTable = QtWidgets.QTableWidget(parent=self.groupBox)
        self.cmdTable.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cmdTable.setFont(font)
        self.cmdTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.cmdTable.setDragDropOverwriteMode(False)
        self.cmdTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.cmdTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.cmdTable.setColumnCount(2)
        self.cmdTable.setObjectName("cmdTable")
        self.cmdTable.setRowCount(0)
        self.cmdTable.horizontalHeader().setDefaultSectionSize(160)
        self.cmdTable.horizontalHeader().setMinimumSectionSize(160)
        self.gridLayout.addWidget(self.cmdTable, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.newCmd = QtWidgets.QPushButton(parent=self.groupBox)
        self.newCmd.setMinimumSize(QtCore.QSize(130, 0))
        self.newCmd.setObjectName("newCmd")
        self.horizontalLayout_2.addWidget(self.newCmd)
        self.editCmd = QtWidgets.QPushButton(parent=self.groupBox)
        self.editCmd.setMinimumSize(QtCore.QSize(130, 0))
        self.editCmd.setObjectName("editCmd")
        self.horizontalLayout_2.addWidget(self.editCmd)
        self.deleteCmd = QtWidgets.QPushButton(parent=self.groupBox)
        self.deleteCmd.setMinimumSize(QtCore.QSize(130, 0))
        self.deleteCmd.setObjectName("deleteCmd")
        self.horizontalLayout_2.addWidget(self.deleteCmd)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.ok = QtWidgets.QPushButton(parent=ProfileEditDialog)
        self.ok.setMinimumSize(QtCore.QSize(130, 0))
        self.ok.setObjectName("ok")
        self.horizontalLayout_3.addWidget(self.ok)
        self.cancel = QtWidgets.QPushButton(parent=ProfileEditDialog)
        self.cancel.setMinimumSize(QtCore.QSize(130, 0))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_3.addWidget(self.cancel)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)

        self.retranslateUi(ProfileEditDialog)
        QtCore.QMetaObject.connectSlotsByName(ProfileEditDialog)

    def retranslateUi(self, ProfileEditDialog):
        _translate = QtCore.QCoreApplication.translate
        ProfileEditDialog.setWindowTitle(_translate("ProfileEditDialog", "Dialog"))
        self.label.setText(_translate("ProfileEditDialog", "Profile:"))
        self.groupBox.setTitle(_translate("ProfileEditDialog", "Commands"))
        self.newCmd.setText(_translate("ProfileEditDialog", "New"))
        self.editCmd.setText(_translate("ProfileEditDialog", "Edit"))
        self.deleteCmd.setText(_translate("ProfileEditDialog", "Delete"))
        self.ok.setText(_translate("ProfileEditDialog", "OK"))
        self.cancel.setText(_translate("ProfileEditDialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfileEditDialog = QtWidgets.QDialog()
    ui = Ui_ProfileEditDialog()
    ui.setupUi(ProfileEditDialog)
    ProfileEditDialog.show()
    sys.exit(app.exec())
